# Generated by Django 4.2.11 on 2024-06-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessmoves',
            name='move',
            field=models.JSONField(),
        ),
    ]
